AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: fetch
      Runtime: go1.x
      Events:
        GetEvent:
          Type: AWS::Serverless::Function
          Properties:
            Path: /
            Method: post